# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56de794c0db2ede5e158b2279f5cea508723a8f508d524b1b2f011dae8ade8eafd359c8f2901b90262c659e21cd2291f742e42d5efaadea4c66e903627dbfbcc

test:
  secret_key_base: b571a3602cec2a6829bc43ba0d19704813f89c9a1b6b92b50e1d9eb6523dcd81e2f85cb7680b0dc308624497cffdfface6bdf9e9d47412dc3a6fbf5e7bf8794d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
